{% set name = "miss3d" %}
{% set version = "6.7" %}
{% set sha256 = "518a9072af34df49015b976345e15251c62820900a2bf2a3088e323bfbab6a61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/prereq/miss3d-{{ version }}_aster4.tar.gz
  sha256: {{ sha256 }}
  patches:
    - Makefile_conda.patch  # [not win]
    - Makefile_conda_win.patch  # [win]
    - Makefile.inc.gnu64_conda.patch  # [not win]
    - Makefile.inc.gnu64_conda_win.patch  # [win]

build:
  number: 6
  detect_binary_files_with_prefix: True   

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib("c") }}    # [win]
  host:
    - make  # [not win]
    - m2w64-make  # [win]
    - liblapack
    - libblas
    - m2-base  # [win]
  run:
    - liblapack
    - libblas
test:
  commands:
    - run_miss3d || true  # [unix]
    - if not exist %PREFIX%\bin\run_miss3d.bat exit 1  # [win]
    - run_miss3d  # [win]

about:
  home: https://www.code-aster.org/spip.php?article98
  license: CECILL-C
  license_family: GPL
  license_file: ./LICENSE.txt
  summary: 'MISS, un outil performant en génie parasismique, dynamique des structures et géophysique'
  description: |
    Soil-Structure Interactions (ISS) and Sol-Fluid-Structure (ISFS) involved in buildings dynamics or in arch dams, 
    can be resolved with frequency coupling in Code_Aster.
    MISS3D (called via the Code_Aster command CALC_MISS) 
    is a code with integral equations (Green functions) and sub-structuring from ECP / LMSSMat .  
  doc_url: https://www.code-aster.org/IMG/UPLOAD/DOC/Telechargement/notice_util_miss3d_v6.4.pdf

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
